// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhqA8YzJM9V4e-v9ZKs4FiEkSiN7m8b68',
    appId: '1:619620435428:web:f1346cbc0b099e38d433f1',
    messagingSenderId: '619620435428',
    projectId: 'hongym-4cb68',
    authDomain: 'hongym-4cb68.firebaseapp.com',
    storageBucket: 'hongym-4cb68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzSL3RbhSzxFWza3VnBwO9MfX40lgoUPY',
    appId: '1:619620435428:android:05e0ba10b4e217bbd433f1',
    messagingSenderId: '619620435428',
    projectId: 'hongym-4cb68',
    storageBucket: 'hongym-4cb68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlh3Y5qIi-41KeAwgAgbA6LtEEYkiOMaw',
    appId: '1:619620435428:ios:8b976829cf28329ed433f1',
    messagingSenderId: '619620435428',
    projectId: 'hongym-4cb68',
    storageBucket: 'hongym-4cb68.appspot.com',
    iosClientId: '619620435428-29i11rc01ppvi45ceipqoh57g1k4jbpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.g2g',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlh3Y5qIi-41KeAwgAgbA6LtEEYkiOMaw',
    appId: '1:619620435428:ios:2d837c502f4bc1c1d433f1',
    messagingSenderId: '619620435428',
    projectId: 'hongym-4cb68',
    storageBucket: 'hongym-4cb68.appspot.com',
    iosClientId: '619620435428-a4r2777upp1mfh13mvcqbi7g5to8ini6.apps.googleusercontent.com',
    iosBundleId: 'com.example.g2g.RunnerTests',
  );
}
